# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de3a13edd094c9f23a68b49ecded72535b10c026cdce1ae0c4070ab1e6d849611c3e0f5effd1f9268294448f595ba83533672d66c0848981d266de74b904e4a9

test:
  secret_key_base: 6c5f288c089571cec31b46926ef490caf6a48f6a0b58036893a24146152d9bfb043e45a44f9fe561dd5fe832b4b3fe90e027a24335fc9c5bb00cbc0083418f0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
